# refer: https://quarkus.io/guides/config-reference
quarkus:
  http:
    host: 0.0.0.0
    port: 5555

greeting:
  imperative: Hello from Imperative
  reactive: Hello from Reactive

static:
  work-dir: ./
  allow-root: false
  list-dir: true